sources:
  - name: DIRECTSALES_STG_LOAD
    database: FIVETRAN
    schema: RAW_DATA_S3
    tables:
        - name: DIRECTSALES_STG_LOAD
  - name: reabte
    database: FIVETRAN
    schema: RAW_DATA_S3
    tables:
      - name: REBATE_STG_LOAD
